spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/zhike
    username: root
    password: 123456
#    url: jdbc:mysql://47.107.58.184:3306/zhike
#    username: zhike
#    password: admin
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 30000
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      enabled: true
      max-request-size: 1MB
      max-file-size: 1MB
server:
  port: 18081
mybatis-flex:
  mapper-locations: mapper/**/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  web:
    resources:
#      static-locations: file:D:\\ck-file
      static-locations: file:./ck-file
  type-aliases-package: com.yun.note.pojo